GOOGLE_APP_SECRET: 'AIzaSyBi2YAJ7iSCF6xbIwS0bZx0JrtufTt4Z0c'
GOOGLE_CLIENT_ID: '957566722607-12g9jsbfjmoiap414jrn00pm36vn465u.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET: 'an-Im5vCEondl5yohKIe8Oz4'
